export const Strings = {
    HOME: 'Home',
    RETOUR: 'Retour',
    TABLE: "Table",
    COMMANDE: 'Commande',
    CUiSINE: 'Cuisine',
    BAR: 'Bar',
    COMMENDES: "Commandes",
    COMMENDES_FIBRE: "Commande Fibre",
    SEARCH_TABLE: "Search Table",
    QUANTITY: "Quantité",
    PRODUCTS: "Produits",
    ACTION: "Action",
    PERSONALISER: "Personaliser",
    APPLICATIONS: "Applications",
    PARAMETERS: "Paramétres",
    FUNCTIONS: "Fonctions",
    A_COTE: "A COTÉ",
    AVEC: "AVEC",
    SANS: "SANS",
    REMPLACER: "REMPLACER",
    KEYBOARD: "KEYBOARD",
    COMMENTS_COMMENTAIRES: "COMMENTS & COMMENTAIRES",
    INSTRUCTION_PRODUCTION: "INSTRUCTION PRODUCTION",
    AJOUTER: "AJOUTER",
    SUPPRIMER: "SUPPRIMER",
    EMAIL: "Email",
    PASSWORD: "Password",
    LOGIN: "Login",
    FORGOT_PASSEORD: "Forgot Password",
    RESET_PASSWORD: "Reset Password",
    VALID_EMAIL: "Please enter valid email",
    EMAIL_REQUIRED: "Email Address is Required",
    PASSWORD_REQUIRED: "Password is Required",
    VALID_PASSWORD: "Password must be at least",
    CHARACTERS: "characters",
    PAUSE: "Pause",
    OFFERT: "offert",
    ENCAISSER: "Encaisser",
    TICKET: "Ticket",
    POURBOIRE: "Pourboire",
    NOTE: "Note",
    DEPLACER: "Deplacer",
    REMISE: "Remise",
    SCAN: "Scan",
    RECHERCHE: "Recherche",
    RESERVATION: "Reservation",
    PARTENAIRE: "Partenaire",
    LIVRAISON: "Livraison",
    CLICK_COLLECT: "Click & Collect",
    CALCULATRICE: "Calculatrice",
    APPEL: "Appel",
    EMPORTER: "Emporter",
    CLIENT: "Client",
    LOGOUT: "Logout",
    STATISTIQUE: "Statistique",
    ESTABLISSEMENT: "Établissement",
    MENU: "Menu",
    RAPPORT: "Rapport",
    PRICE: "Price",
    SUB_TOTAL: "Sub-total",
    GST: "GST",
    TOTAL: "Total",
    CONFIRMER_ET_ENVOYER: "Confirmer et envoyer",
    ORDER_SUCCESSFUL: "Order Successfully Place",
    NEW_ORDER: "New Order",
    NO_DATA_FOUND: "No Data Found",
    NO_TABLE_FOUND: "No Table Found",
    ADD_QUANTITY: "Add Quantity",
    DONE: "Done",
    FORGOT_PASSEORD_EMAIL: "Email sent successfully, please check your email",
    MORE: "More",
    GOHOME: "Go To Home"

}
